import sys
import os
from math import gcd

import numpy as np
from scipy.io import wavfile
from scipy.signal import fftconvolve, resample_poly
import soundfile as sf

NCC_THRESHOLD = float(os.getenv("NCC_THRESHOLD", "0.22"))
NCC_MARGIN = float(os.getenv("NCC_MARGIN", "0.12"))


def read_audio(path):
    try:
        sr, data = wavfile.read(path)
    except Exception:
        # Fallback for formats like WAV-MULAW generated by PBX recordings
        data, sr = sf.read(path, dtype="float32", always_2d=False)
        if isinstance(data, np.ndarray) and data.ndim > 1:
            data = np.mean(data, axis=1)
        data = np.asarray(data, dtype=np.float32)
        data = data - np.mean(data)
        return int(sr), data

    if data.ndim > 1:
        data = np.mean(data.astype(np.float32), axis=1)

    if data.dtype == np.int16:
        data = data.astype(np.float32) / 32768.0
    elif data.dtype == np.int32:
        data = data.astype(np.float32) / 2147483648.0
    elif data.dtype == np.uint8:
        data = (data.astype(np.float32) - 128.0) / 128.0
    else:
        data = data.astype(np.float32)
        peak = np.max(np.abs(data)) if data.size else 1.0
        if peak > 1.0:
            data /= peak

    # Remove DC component
    data = data - np.mean(data)
    return sr, data


def resample_if_needed(x, src_sr, dst_sr):
    if src_sr == dst_sr:
        return x
    g = gcd(src_sr, dst_sr)
    up = dst_sr // g
    down = src_sr // g
    return resample_poly(x, up, down).astype(np.float32)


def trim_reference(ref, sr):
    if ref.size == 0:
        return ref
    env = np.abs(ref)
    thr = max(0.03 * float(np.max(env)), 1e-4)
    idx = np.where(env >= thr)[0]
    if idx.size == 0:
        return ref
    pad = int(0.02 * sr)
    start = max(int(idx[0]) - pad, 0)
    end = min(int(idx[-1]) + pad + 1, ref.size)
    return ref[start:end]


def peak_normalized_cross_correlation(signal, template):
    n = signal.size
    m = template.size
    if m == 0 or n < m:
        return 0.0, -1, np.array([], dtype=np.float64)

    t = template.astype(np.float64)
    t = t - np.mean(t)
    t_norm = np.linalg.norm(t)
    if t_norm < 1e-12:
        return 0.0, -1, np.array([], dtype=np.float64)

    x = signal.astype(np.float64)
    dots = fftconvolve(x, t[::-1], mode="valid")

    csum = np.concatenate(([0.0], np.cumsum(x)))
    csum2 = np.concatenate(([0.0], np.cumsum(x * x)))

    win_sum = csum[m:] - csum[:-m]
    win_sum2 = csum2[m:] - csum2[:-m]
    win_var = win_sum2 - (win_sum * win_sum) / m
    win_var = np.maximum(win_var, 1e-12)
    denom = np.sqrt(win_var) * t_norm

    ncc = dots / denom
    peak_idx = int(np.argmax(ncc))
    return float(ncc[peak_idx]), peak_idx, ncc


def robust_peak_score(ncc):
    if ncc.size == 0:
        return 0.0, 0.0, 0.0
    med = float(np.median(ncc))
    mad = float(np.median(np.abs(ncc - med))) + 1e-9
    robust_sigma = 1.4826 * mad
    peak = float(np.max(ncc))
    z = (peak - med) / robust_sigma
    return peak, med, z


def analyze_injection(recording_path, reference_path):
    try:
        rec_sr, rec = read_audio(recording_path)
        ref_sr, ref = read_audio(reference_path)

        ref = trim_reference(ref, ref_sr)
        ref = resample_if_needed(ref, ref_sr, rec_sr)

        peak, peak_idx, ncc = peak_normalized_cross_correlation(rec, ref)
        peak, median, robust_z = robust_peak_score(ncc)
        peak_time = (peak_idx / rec_sr) if peak_idx >= 0 else -1.0

        print(f"[*] Recording: {recording_path}")
        print(f"[*] Reference: {reference_path}")
        print(f"[*] Recording SR: {rec_sr} Hz")
        print(f"[*] Reference length (trimmed/resampled): {ref.size / rec_sr:.3f} s")
        print(f"[*] Peak NCC: {peak:.4f}")
        print(f"[*] NCC median: {median:.4f}")
        print(f"[*] Robust peak score (z): {robust_z:.2f}")
        print(f"[*] Thresholds: NCC>={NCC_THRESHOLD:.3f}, (NCC-median)>={NCC_MARGIN:.3f}")
        if peak_time >= 0:
            print(f"[*] Best match at: {peak_time:.3f} s")

        # Decision rule:
        # - peak NCC catches waveform similarity with the injected sample
        # - peak-minus-median keeps the decision stable when NCC distribution is broad
        if peak >= NCC_THRESHOLD and (peak - median) >= NCC_MARGIN:
            print("[CONFIRMED] RTP injection detected (reference match found).")
            sys.exit(0)
        else:
            print("[CLEAN] No reliable RTP injection match found.")
            sys.exit(1)

    except Exception as exc:
        print(f"Error: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python verify.py <path_to_recording_wav> [path_to_reference_wav]")
        sys.exit(1)

    recording = sys.argv[1]
    reference = sys.argv[2] if len(sys.argv) >= 3 else "/references/audio_inject.wav"
    analyze_injection(recording, reference)
