services:
  kamailio:
    build: ./kamailio
    image: kamailio
    networks:
      lab_net:
        ipv4_address: ${KAMAILIO_IP:-10.13.0.5}
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  sipp101:
    build: ./sipp
    image: sipp101
    tty: true
    depends_on:
    - kamailio
    volumes:
    - ./sipp/xml/registration101.xml:/sipp/xml/registration101.xml
    - ./sipp/xml/overflow.xml:/sipp/xml/overflow.xml
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    networks:
      lab_net:
        ipv4_address: ${SIPP_IP:-10.13.0.10}
networks:
  lab_net:
    driver: bridge
    ipam:
      config:
      - subnet: ${LAB_SUBNET:-10.13.0.0/24}
