[internal]
exten => _700[12],1,NoOp(Recording bridged call for ${CALLERID(num)} to ${EXTEN})
 same => n,Set(RECORD_FILE=${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-${CALLERID(num)}-to-${EXTEN}-${UNIQUEID})
 same => n,MixMonitor(${RECORD_FILE}.wav,b)
 same => n,Dial(SIP/${EXTEN},300)
