[general]
allowguest=no
bindport=5060
bindaddr=0.0.0.0
disallow=all
allow=ulaw
alwaysauthreject=yes
directmedia=no
nat=force_rport,comedia
localnet=10.10.181.0/24
externaddr=10.10.181.5

[7001]
type=peer
host=dynamic
secret=7001
context=internal
nat=force_rport,comedia

[7002]
type=peer
host=dynamic
secret=7002
context=internal
nat=force_rport,comedia
